environments:
  benrd:
  bingrd:
  dev:
  prod-blue:
  prod-green:
  prototype:


releases:

  - name: alwaysonbotapi-{{ requiredEnv "BRANCH" }}
    chart: ../helm/charts/always-on-bot-bdm-dev
    namespace: always-on-bot-backend-{{ requiredEnv "BRANCH" }}
    values:
      - overrides/always-on-bot-bdm-dev-api.yaml.gotmpl
    labels:
        category: prototype
        app: always-on-bot-bdm-dev
        tier: api
    wait: false
    installed: true
    force: false